config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/subscriptions' => 'subscriptions#index'
  post '/subscriptions/subscribe' => 'subscriptions#subscribe'
  post '/subscriptions/custom_subscribe' => 'subscriptions#custom_subscribe'
  get 'subscriptions/user_invoice' => 'subscriptions#invoice', as: 'invoice_pdf'

  post 'braintree_webhook' => 'braintree_webhook#webhook'

  resources :products, only: %i[index show]
  post '/products/buy' => 'products#buy'
  root to: 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/braintree_invoice.rb
require 'render_anywhere'

class BraintreeInvoice
  include RenderAnywhere

  def initialize(transaction)
    @transaction = transaction
  end

  def filename
    'invoice.pdf'
  end

  def to_pdf
    kit = PDFKit.new(as_html, page_size: 'A4')
    kit.to_file("#{Rails.root}/public/invoice.pdf")
  end

  private def as_html
    render template: 'subscriptions/invoice', layout: 'invoice_pdf', locals: { transaction: @transaction, customer: @transaction.customer_details, card: @transaction.credit_card_details }
  end
end

app/models/braintree_webhook_handler.rb
class BraintreeWebhookHandler
  attr_reader :notification

  delegate :subscription, to: :notification
  delegate :kind, to: :notification

  def initialize(bt_signature, bt_payload)
    @notification = Braintree::WebhookNotification.parse(
      bt_signature,
      bt_payload
    )
  end

  def call
    case kind
    when Braintree::WebhookNotification::Kind::SubscriptionCanceled
      handle_subscription_canceled
    else
      log_unhandled_kind
    end
  end

  def db_subscription
    Subscription.find_by(braintree_subscription_id: subscription.id)
  end

  def handle_subscription_canceled
    Rails.logger.info "#{self.class} - #{__method__}"
    handle_common
  end

  def log_unhandled_kind
    Rails.logger.warn "[webhooks] Unhandled braintree webhook kind: #{kind}"
  end

  private def handle_common
    if db_subscription
      db_subscription.sync!(subscription)
    else
      Rails.logger.warn "Couldn't find BraintreeSubscription for #{subscription.id}"
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user

  def sync!(subscription)
    update_attributes(
      status: subscription.status
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email password password_confirmation first_name last_name phone])
  end

  def generate_braintree_client_token
    if user_signed_in?
      result = Braintree::Customer.create(
        first_name: current_user.first_name,
        last_name: current_user.last_name,
        email: current_user.email,
        phone: current_user.phone
      )
      customer_id = result.customer.id
      current_user.update(customer_id_braintree: customer_id)
      Braintree::ClientToken.generate(customer_id: customer_id)
    end
  end
end

app/controllers/braintree_webhook_controller.rb
class BraintreeWebhookController < ApplicationController
  skip_before_action :verify_authenticity_token

  def webhook
    BraintreeWebhookHandler.new(bt_signature_param, bt_payload_param).call
    head :ok
  end

  private

  def bt_signature_param
    params[:bt_signature]
  end

  def bt_payload_param
    params[:bt_payload]
  end

  def bt_challenge_param
    params[:bt_challenge]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    gon.client_token = generate_braintree_client_token
    @product = Product.find(params[:id])
  end

  def index
    @products = Product.all
  end

  def buy
    result = Braintree::Transaction.sale(
      amount: params[:amount],
      payment_method_nonce: params[:payment_method_nonce],
      options: {
        submit_for_settlement: true
      }
    )
    if result.success?
      redirect_back(fallback_location: root_path, notice: 'Everything was fine!')
    else
      redirect_back(fallback_location: root_path, notice: 'Something went wrong! :/')
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  def index
    gon.client_token = generate_braintree_client_token
    @subscriptions = Subscription.all
  end

  def show; end

  def custom_subscribe
    result_payment = Braintree::PaymentMethod.create(
      customer_id: current_user.customer_id_braintree,
      payment_method_nonce: params[:payment_method_nonce]
    )

    if result_payment.success?
      result = Braintree::Subscription.create(
        payment_method_token: result_payment.payment_method.token,
        plan_id: params[:plan_id]
      )
      handle_result_subscription(result)
    else
      redirect_back(fallback_location: root_path, notice: 'Something went wrong creating your payment method! :/')
    end
  end

  def invoice
    if params[:transaction_id]
      transaction = Braintree::Transaction.find(params[:transaction_id])
      respond_to do |format|
        format.pdf { send_invoice_pdf(transaction) }
      end
    else
      redirect_to subscriptions_path, notice: 'No invoices yet'
    end
  end

  def subscribe
    result = Braintree::Subscription.create(
      payment_method_nonce: params[:payment_method_nonce],
      plan_id: params[:plan_id]
    )

    handle_result_subscription(result)
  end

  private def send_invoice_pdf(transaction)
    invoice_pdf = BraintreeInvoice.new(transaction)
    send_file invoice_pdf.to_pdf,
      filename: invoice_pdf.filename,
      type: 'application/pdf',
      disposition: 'inline'
  end

  private def handle_result_subscription(result)
    if result.success?
      Subscription.create(amount: params[:amount], user: current_user,
                          plan_id: result.subscription.plan_id,
                          status: result.subscription.status,
                          braintree_transaction_id: result.subscription.transactions.last.id,
                          braintree_subscription_id: result.subscription.id)
      redirect_back(fallback_location: root_path, notice: 'Everything was fine!')
    else
      redirect_back(fallback_location: root_path, notice: 'Something went wrong! :/')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPayments</title>
    <%= Gon::Base.render_data %>
    <%= csrf_meta_tags %>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g="
    crossorigin="anonymous"></script>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">
    <% if user_signed_in? %><a href="#"><%= current_user.email %></a><% end %>
    <% if user_signed_in? %>
      <%= link_to "Sair", destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to new_user_session_path do %>
        Entrar
      <% end %>
    <% end %>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/invoice_pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Invoice from Braintree</title>
  <style>
    body {
      font-size: 3rem;
      font-family: "Montserrat", Helvetica, sans-serif;
    }
    .invoice-billto {
      display: flex;
      margin-left: 2%;
      margin-top: 4rem;
    }
    .invoice-billto div {
      display: inline-block;
      vertical-align: top;
      width: 31.7%;
    }
    .invoice-billto h3 {
      color: rgba(74, 74, 74, 0.6);
      font-size: 4rem;
      font-weight: 900;
    }
    .invoice-billto p {
      color: rgba(74, 74, 74, 0.9);
      font-family: "Montserrat", Helvetica, sans-serif;
      font-size: .85rem;
      margin: 0 auto;
    }
    .box {
      border: 2px solid;
      border-radius: 0.2rem;
      padding 1rem;
    }
    .amount {
      font-size: 5rem;
    }
  </style>
  <meta charset="utf-8">
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/products/index.html.erb
<div>
  <h1>All Products</h1>

  <% @products.each do |p| %>
    <div>
      <img src="<%= p.image_url %>" width="100" height="100" />
      <p>
        <%= link_to p.name, product_path(p) %>
        $<%= p.amount %>
      </p>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<script src="https://js.braintreegateway.com/v2/braintree.js"></script>
<script>
 braintree.setup(gon.client_token, 'dropin', { container: 'dropin', form: 'buy_product_form' });
</script>
<div>
  <h1><%= @product.name %></h1>
  <div>
    <img src="<%= @product.image_url %>" width="100" height="100" />
  </div>
  <b>$<%= @product.amount %></b>

  <div class="form-container">
    <h2>Checkout</h2>
    <%= form_tag products_buy_path, id: 'buy_product_form' do%>
      <%= hidden_field_tag :amount, @product.amount %>
      <p>Please enter your payment details:</p>
      <div id="dropin"></div>
      <%=submit_tag "Pay #{@product.amount}$", class: "btn" %>
    <%end%>
  </div>
</div>

app/views/subscriptions/index.html.erb
<script src="https://js.braintreegateway.com/v2/braintree.js"></script>
<script>
  //Drop in
  braintree.setup(gon.client_token, 'dropin', { container: 'dropin_monthly', form: 'dropin_monthly' });
  braintree.setup(gon.client_token, 'dropin', { container: 'dropin_annual', form: 'dropin_annual' });
  // Custom
  braintree.setup(gon.client_token, 'custom', { id: 'custom_form_monthly'});
  braintree.setup(gon.client_token, 'custom', { id: 'custom_form_annual'});
</script>

<div>
  <h2>All Subscriptions</h2>

  <ul>
    <% @subscriptions.each do |subscription| %>
      <li><%= subscription.plan_id %> - <%= subscription.amount %> - <%= subscription.status %> - <%= link_to "Get Invoice", invoice_pdf_path(format: 'pdf', transaction_id: subscription.braintree_transaction_id) %></li>
      <% end %>
  </ul>

  <h1> Customised</h1>
  <h3> Subscribe to a plan </h3>

  <div class="well">
    <div class="form-container">
      <%= form_tag subscriptions_custom_subscribe_path, method: :post, id: 'custom_form_monthly' do %>
        <p>Please enter your payment details:</p>
        <%= hidden_field_tag :plan_id, 'monthly' %>
        <%= hidden_field_tag :amount, '10' %>
        <input data-braintree-name="number" value="4111111111111111">
        <input data-braintree-name="expiration_date" value="10/20">
        <%= submit_tag "Subscribe to monhtly plan - $10", class: "btn btn-large" %>
      <% end %>
    </div>
  </div>

  <div class="well">
    <div class="form-container">
      <%= form_tag subscriptions_custom_subscribe_path, method: :post, id: 'custom_form_annual' do %>
        <p>Please enter your payment details:</p>
        <%= hidden_field_tag :plan_id, 'annual' %>
        <%= hidden_field_tag :amount, '200' %>
        <input data-braintree-name="number" value="4111111111111111">
        <input data-braintree-name="expiration_date" value="10/20">
        <%= submit_tag "Subscribe to annual plan - $200", class: "btn btn-large" %>
      <% end %>
    </div>
  </div>


  <h1> Drop In UI </h1>
  <h3> Subscribe to a plan </h3>

  <div class="well">
    <div class="form-container">
      <%= form_tag subscriptions_subscribe_path, method: :post, id: 'dropin_monthly' do %>
        <p>Please enter your payment details:</p>
        <div id="dropin_monthly"></div>
        <%= hidden_field_tag :plan_id, 'monthly' %>
        <%= hidden_field_tag :amount, '10' %>
        <%= submit_tag "Subscribe to monhtly plan - $10", class: "btn btn-large" %>
      <% end %>
    </div>
  </div>

  <div class="well">
    <div class="form-container">
      <%= form_tag subscriptions_subscribe_path, method: :post, id: 'dropin_annual' do %>
        <p>Please enter your payment details:</p>
        <%= hidden_field_tag :plan_id, 'annual' %>
        <div id="dropin_annual"></div>
        <%= hidden_field_tag :amount, '200' %>
        <%= submit_tag "Subscribe to annual plan - $200", class: "btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/subscriptions/invoice.html.erb
<div class="invoice-header">
  <h1> My Company name here</h1>
</div>

<div class="invoice-billto">
  <div class"bill-to">
    <h3> Customer Information</h3>
    <ul>
      <li><b><%= customer.first_name %> <%= customer.last_name %></b></li>
      <li><b>Email:</b> <%= customer.email %></li>
      <li><b>Phone:</b> <%= customer.phone %></li>
      <li><b>Location:</b> <%= transaction.credit_card_details.customer_location %></li>
    </ul>
  </div>
</div>

<hr/>
<h3>Details</h3>
<div class="box">
  <h4>Amount: <span class="amount"><%= transaction.amount %> USD</span></h4>
  <div>
    <b>Last 4 digits:</b> <%= card.last_4 %>
    <b>Expiration date:</b> <%= card.expiration_date %>
    <img src="<%=card.image_url%>"/>
  </div>
</div>